CREATE TABLE CERTIFICADODIGITAL
(
  NOMBRE varchar(32) NOT NULL,
  CLAVE varchar(32),
  VIGENCIAINICIO date,
  VIGENCIAFIN date,
  ARCHIVO blob sub_type 0,
  ACTIVO smallint,
  CONSTRAINT INTEG_366 PRIMARY KEY (NOMBRE)
);
